### ISSUE TITLE
Use contextual alternates instead of ligatures

### ISSUE THREAD

**Issue by idan** [i-tu/Hasklig#40]
This would enable cursor positioning "inside" ligatures in atom (see [this](https://github.com/i-tu/Hasklig/issues/7#issuecomment-152477328) and [this](https://github.com/atom/atom/issues/3821#issuecomment-146433091)). Would also help with #18.

I really love hasklig but the unintuitive insertion point behavior around the combination glyphs sends me back to plain Source Code Pro. :cry: 

Thanks for making Hasklig! :heart:

**Comment by i-tu** [comment]
Hey @idan , this is in the works :)

**Comment by idan** [comment]
:tada: most excellent. Thank you!

**Comment by idan** [comment]
In the meantime, I'm using this with the following stylesheet to disable ligatures on editing lines (partially cribbed from Monoid's recommended stylesheet changes for atom):

```less
atom-text-editor {
  text-rendering: optimizeLegibility;
  -webkit-font-feature-settings: "liga" on, "calt" on;
}

atom-text-editor::shadow {
  .cursor-line {
    -webkit-font-feature-settings: "liga" off, "calt" off;
  }
}

div.find-and-replace atom-text-editor::shadow .line {
  -webkit-font-feature-settings: "liga" off, "calt" off;
}

div.project-find atom-text-editor::shadow .line {
  -webkit-font-feature-settings: "liga" off, "calt" off;
}
```
